### ISSUE TITLE
Doesn't Seem to work with presence footsteps

### ISSUE THREAD

**Issue by Benzeel** [thedocruby/resounding#77]
**Describe the bug**

no sound reverb or effects when presence footsteps enabled / installed. (it might only be for multiplayer as far as I know, but I'm not sure as I already removed presence footsteps.)

**To Reproduce**
1. install presence footsteps & resounding
2. join a server or go into a world, find a cave and walk around
3. no reverb for sounds

**Expected behavior**
A clear and concise description of what you expected to happen but did not.

have presence footsteps installed and have proper sound physics

**My Machine (please complete the following information):**
 - OS: Windows 10 Home
 - Minecraft Version: 1.18.2
 - Mod version: 1.0.0-bc.9
 - Mods list:
 https://limey.is-ne.at/5x35yLNnh.png

**Additional context**

problem only occured when presence footsteps was installed

**Comment by Benzeel** [comment]
i forgot to add the compatibility tag, i apologize

**Comment by imabigdipper** [comment]
Strange, both mods work fine for me both client and server side

**Comment by Benzeel** [comment]
what versions?

**Comment by mikenrafter** [comment]
The same bug as #52. I know the reason. It's the raytracing code that needs a rework. The reason that normal footsteps work is because of a temporary ducktape solution - all footsteps are moved up by .2 or .5ish blocks. So their raytracing isn't problematic. The footstep detection code doesn't understand presence footsteps' sound names, and therefore the same is not applied to them.

This will be fixed in a future release. Once the raytracing has been reworked.
