### ISSUE TITLE
Resounding VS SoundPhysics

### ISSUE THREAD

**Issue by FrostBlade5** [thedocruby/resounding#83]
I have been using SoundPhysics v0.5.6 and it was a great mod.
Now im not sure if i should switch to Resounding instead because this mod clearly says it's an ALPHA version with BUGS.

What do you recommend and what are the differences? What do you mean by "immersive"?

**Comment by mikenrafter** [comment]
Resounding works pretty well in my experience, though it is in alpha, and it hasn't been thoroughly tested as such.  
Right now, the biggest user-facing difference for resounding vs sound physics is A - performance (multithreading), and B - missing features.

Resounding is set to surpass Sound Physics in features, but as of right now, it's not at feature parody. Hence, it's in alpha. Reverb and basic occlusion (and water filter) are implemented, though.

Immersion (relating to video games) is how believable something in a game is. When it's more believable, the user doesn't focus on it and think "huh, weird, that seemed off...". Minecraft isn't the most immersive game, it's blocky, but it can be beautiful, and when small things like [proper damage tilt](https://www.curseforge.com/minecraft/mc-mods/damage-tilt) are added, the game just feels more natural. The same thing happens when you have reverb, or echo, or resonance, etc. So Resounding adds immersion to the game by making sounds more realistic. You used SoundPhysics... so, you know the feeling, when breaking a block, inside a cave and hearing the *resounding* effect it has throughout the cave (reverb). It's that feeling...

Conclusion? Decide for yourself, it's useable, but not perfect - as it will be in the future.

**Comment by FrostBlade5** [comment]
Thanks, i will switch to resounding in the future.

**Comment by mikenrafter** [comment]
Closing this, as it's more of a question, than an issue. Please use the [discord](https://discord.gg/kdZ6gH7Hg6) if you have further questions.
